# -*- coding: utf-8 -*-
"""Ficha 02 - Aula 04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pbxUFQ_uXiQu_BU1542c7vVCDnsYFv26

# ATIVIDADE DE OPERAÇÕES BÁSICAS DE LISTAS

Crie uma lista chamada ‘numeros’ contendo os números de 0 a 10;
"""

numeros = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(f"Número de 0 à 10:, {numeros}")

"""Imprima na tela o tamanho da lista usando o comando print( );"""

numeros = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print("Acessando pelo índice:", len(numeros))

"""Crie uma lista com 4 nomes quaisquer;

"""

nomes = ["Alisson", "Vinicius", "Will", "Sophia"]
print(nomes)

"""Imprima na tela os 4 nomes da lista que você criou usando a estrutura ‘for’.

"""

nomes = ["Alisson", "Vinicius", "Will", "Sophia"]
for nome in nomes:
  print(f"Nomes:{nomes}")

"""Copie esta lista: [1, “teste”, 8.67, 90, “casa”, ‘a’, 12.34, 1, 0, “bola”, False, 23, “hello”] para uma variável chamada  ‘diversos’. Em seguida, informe na tela a mensagem: “O tamanho dessa lista é ____”. (Obs. caso você copie e o VScode acuse erro, digite as aspas novamente)."""

diversos = [1, "teste", 8.67, 90, "casa", "a", 12.34, 1, 0, "bola", False, 23, "hello"]
tamanho_lista = len(diversos)
print("O tamanho dessa lista é:", tamanho_lista)

"""Com a lista acima em seu editor de códigos, imprimia na tela todos os itens dessa lista. (Use o ‘for’)"""

diversos = [1, "teste", 8.67, 90, "casa", "a", 12.34, 1, 0, "bola", False, 23, "hello"]
print("Itens da lista:")
for itens in diversos:
  print(itens)

"""Ainda com a mesma lista acima, imprima os tipos dos dados de todos os itens dessa lista. (Obs. Pesquise rapidamente como saber o tipo de um dado em python usando a função type( ))"""

diversos = [1, "teste", 8.67, 90, "casa", "a", 12.34, 1, 0, "bola", False, 23, "hello"]
for itens in diversos:
  print("Tipo de dado:", type(itens))

"""Com a lista acima, acesse diretamente o item 7, e imprima na tela a mensagem: “O elemento ____ é do tipo ____”;"""

diversos = [1, "teste", 8.67, 90, "casa", "a", 12.34, 1, 0, "bola", False, 23, "hello"]
print(f"O elemento{diversos[7]} é do tipo:{type(diversos[7])}")

"""Imprima a lista ‘diversos’ na tela, em seguida atribua o valor “hello world” ao item 4. Imprima a lista inteira novamente. (Para atribuir um valor em um item específico de uma lista use lista[indice] = valor) ;"""

diversos = [1, "teste", 8.67, 90, "casa", "a", 12.34, 1, 0, "bola", False, 23, "hello"]
print(diversos)
diversos[4] = "Hello world"
print(diversos)

"""# PRINCIPAIS MÉTODOS EM  LISTAS

Crie uma lista vazia. Em seguida utilize o método append( ) para adicionar 4 elementos;
"""

lista = []
print(lista)
lista.append("Alisson")
lista.append("Will")
lista.append("Sophia")
lista.append("Vinicius")
print(f"nomes: {lista}")

"""Crie um ‘for’ de varie no intervalo de 1 a 10. Em seguida adicione cada número desses em uma lista criada previamente."""

numero = []
for i in range(2,11,7):
  numero.append(i)
print(numero)

"""Crie um algoritmo que solicite ao usuário 3 nomes. Adicione os nomes a uma lista. Em seguida, imprima um a um esses nomes na tela."""

lista = []
for i in range(3):
  lista.append(input("Fale um nome:"))
for nome in lista:
  print(f"Nomes na lista: {nome}")

"""Crie e nomeie a lista [1, 2, 3, 4] no seu editor de texto. Em seguida insira o valor 0 no início da lista e o valor 5 no final da lista;"""

numeros = [1,2,3,4]
print(numeros)
numeros.insert(0,0)
numeros.append(5)
print(numeros)
numeros[3] = "hello"
print(numeros)

"""Com a mesma lista acima, remova o item ‘3’, e insira em seu lugar o texto ‘hello’

"""

numeros = [1,2,3,4]
print(numeros)
numeros.insert(0,0)
numeros.append(5)
print(numeros)
numeros[3] = "Hello"
print(numeros)

"""Crie um laço que permaneça executando enquanto o usuário digitar um número diferente de 0. A cada valor diferente de zero imprima “Você digitou ___” e adicione esse valor a uma lista. No final quando o usuário digitar 0, imprimia, “Você digitou 0, o programa foi encerrado”. E imprima a lista com todos os números digitados pelo usuário."""

secreto = 0
lista = []
resposta = 7
while resposta != secreto:
  resposta = int(input("Tente descobrir a chave secreta:"))
  lista.append(resposta)
  if resposta !=0:
    print(f"Você digitou: {resposta},Acertou a chave secreta")
    print(f"Você descobriu a chave secreta, programa encerrado. \nDurante o programa você digitou: {lista}")

"""Crie uma lista contendo todos os números pares entre 0 e 20 e adicione todos em uma lista chamada ‘pares’. Em seguida, use o método pop( ) e remova o elemento no índice 4 e mostre a mensagem: “O elemento 4 é o ____”."""

pares = []
for i in range(0,20,1):
  if i % 2 == 0:
    pares.append(i)

print(pares)
ret = pares.pop(4)
print(f"O elemento no índice 4 é: {ret}, lista: {pares}")

"""Crie uma lista chamada nomes, contendo 5 nomes quaisquer. Em seguida, extraia uma sub-lista contendo do segundo ao quarto nome. """

nomes = ["Alisson", "Will", "Sophia", "Clarissa", "Teresa"]
sub = nomes[1:4]
print(sub)

"""Solicite ao usuário que informe 10 números inteiros. Armazene em uma lista. Em seguida, imprima a lista ordenada de forma crescente e também decrescente."""

lista = []
for i in range(0,10,1):
  numeros = int(input("Informe 10 números:"))
  lista.append(numeros)
print("Ordem crescente dos números" ,sorted(lista))
print(" Ordem descrecente dos números:" ,sorted(lista, reverse = True))

"""Utilizando listas, faça um programa que faça 5 perguntas para uma pessoa sobre um crime. O usuário deve digitar 0 para não e 1 para sim. As perguntas são:

* "Telefonou para a vítima?"
* "Esteve no local do crime?"
* "Mora perto da vítima?"
* "Devia para a vítima?"
* "Já trabalhou com a vítima?" 

O programa deve no final emitir uma classificação sobre a participação da pessoa no crime. 
Se a pessoa responder positivamente a 2 questões ela deve ser classificada como "Suspeita", entre 3 e 4 como "Cúmplice" e 5 como "Assassino". Caso contrário, ele será classificado como "Inocente". Utilize a estrutura:

perguntas = ["Telefonou para a vítima?", "Esteve no local do crime?", "Mora perto da vítima?",  "Devia para a vítima?", "Já trabalhou com a vítima?" ]
respostas = [ ]
"""

respostas = []
perguntas = ["Telefonou para a vítima?", "Esteve no local do crime?", "Mora perto da vítima?", "Devia para a vítima?", "Já trabalhou com a vítima?"]
for p in perguntas:
  res = int(input(f"{p}\nEscolha 0 para não e 1 para sim."))
  respostas.append(res)
sim = respostas.count(1)
if sim == 2:
  print("Participação no crime: Suspeita.")
elif sim == 3 or sim == 4:
  print("Participação no crime: Cúmplice.")
elif sim == 5:
  print("Participaçã no crime: Assassino.")
else:
  print("Inocente.")

"""# PRINCIPAIS OPERAÇÕES COM TUPLAS

Declare uma tupla vazia , uma contendo 5 nomes a sua escolha e uma contendo um único email.
"""

tupla_nomes = ("Alisson", "Will", "Sophia", "Teresa", "Clarissa")
tupla_email = ("alissonjose_57@hotmail.com")

print(tupla_nomes)
for nome in tupla_nomes:
print(f"O nome: {nome} está armazenado no índice {tupla_nomes.index(nomes)}")

"""Dada a seguinte tupla: (“José”, 35, 1.78, “jose@email.com”). Faça o desempacotamento dessa tupla em variáveis individuais. Escolhas nomes coerentes com o problema."""

nome, login, email = "Alisson", "Ali", "alissonjose07@gmail.com"
tupla_usuario = (nome, login, email)
for item in tupla_usuario:
  print(f" Itens na tupla: {item}")

"""# VAMOS UNIR OS CONHECIMENTOS

Elaborar um algoritmo que solicite os seguintes dados de três usuários: nome, email e telefone. Em seguida armazene esses valores em uma tupla.
"""

import email
import logging


tupla_nomes = (nomes)
tupla_login = login
tupla_email = emails
tupla_telefone = telefones
for i in range(0,3,1):
    nomes = input("Informe seu nome:")

"""Elabore um algoritmo que solicite a três  usuário os seguintes dados: idade, login e senha. Primeiro insira esses dados em uma tupla. Depois insira cada tupla em uma lista. Por sim, percorra toda lista, desempacotando cada tupla e mostrando a seguinte mensagem para cada usuário: “O usuário ___ foi cadastrado com sucesso. Login: ___ e Senha: ___”."""



"""Elaborar um algoritmo que que solicite de 3 usuários, nome, altura e peso. Armazena esses valores em uma tupla, mas adicione nesta tupla o resultado do IMC deste usuário. Em outro for, percorra a lista e indique para cada usuário sua situação corporal conforme legenda: <18 abaixo do peso, entre 18 e 25 peso ideal, 26 a 30 sobre-peso, acima de 30 obeso."""

tupla_pessoa = ("Sophia", 26, 1.75, "sophiacalvacanti@gmail.com")
nome, id, alt, email = tupla_pessoa
print(f"Dados do usuário: {tupla_pessoa}")
print(f"Nome do usuário:{nome} \nIdade do usuário: {id}\nAltura do usuário:{alt}\nEmail do usuário:{email}")

"""Crie um algoritmo que leia o resultado de cada uma das 10 questões do usuário em uma prova. O usuário irá informar 1 se ele acertou e -1 se ele errou. Adicione cada uma das respostas em uma lista de respostas. Em outro for percorra a lista somando as notas  e depois mostre a mensagem: “Nota final ___” (Lembre do conceito de acumulador)"""

